[package]
org = "lianewso2"
name = "critical_appointment_integration"
version = "0.1.0"

[build-options]
sticky = true

[[platform.java21.dependency]]
groupId = "com.ibm.mq"
artifactId = "com.ibm.mq.allclient"
version = "9.4.1.0"